name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull adautovjr/how-much-left-discord-bot:latest
      
      - name: Delete old image
        run: docker rm -f adautovjr/how-much-left-discord-bot:latest || true

      - name: Deploy with Docker Compose
        run: |
          docker compose down
          docker compose up -d