name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login Dockerhub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $DOCKERHUB_USERNAME --password-stdin $DOCKERHUB_PASSWORD

      - name: Pull Docker image
        run: docker pull how-much-left-discord-bot:latest
      
      - name: Delete old image
        run: docker rm -f how-much-left-discord-bot:latest || true

      - name: Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose up -d