name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up .env file
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "CHANNEL_ID=${{ secrets.CHANNEL_ID }}" >> .env
      
      - name: Build Docker image
        run: docker build -t adautovjr/clansados-discord-bot:latest .

      - name: Push to Dockerhub
        run: docker push adautovjr/clansados-discord-bot:latest